version: 2
updates:
  - package-ecosystem: npm
    directory: /github-release-download
    schedule:
      interval: weekly
  - package-ecosystem: npm
    directory: /set-environment-variables
    schedule:
      interval: weekly
  - package-ecosystem: npm
    directory: /setup-terraform
    schedule:
      interval: weekly
