name: Test
on:
  push:
    branches:
      - master
    tags:
      - "v*"
  pull_request: {}
jobs:
  test:
    name: Testing
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: GitHub Release Download
        uses: ./github-release-download
        with:
          repo: mesa-cli
          tool: mesa
          githubToken: ${{ secrets.CI_GITHUB_TOKEN }}
      - run: mesa --version
      - name: Set Environment
        uses: ./set-environment-variables
        env:
          RANDOM_ENV: foo
          ANOTHER_VAR: bar
        with:
          variables: RANDOM_ENV,ANOTHER_VAR
      - name: Read Environment
        run: |
          [ "$RANDOM_ENV" = "foo" ]
          [ "$ANOTHER_VAR" = "bar" ]
